In [3]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer
#knn = KNNImputer(n_neighbors = 5, add_indicator=-True)
#df = pd.read_csv('vhv_T6.csv')

In [10]:
df.isnull()

Unnamed: 0.2  Unnamed: 0.1  Unnamed: 0  income  subjective_class  \
0           False         False       False   False             False   
1           False         False       False   False             False   
2           False         False       False   False             False   
3           False         False       False   False             False   
4           False         False       False   False             False   
..            ...           ...         ...     ...               ...   
570         False         False       False   False             False   
571         False         False       False   False             False   
572         False         False       False   False             False   
573         False         False       False   False             False   
574         False         False       False   False             False   

     income_enough  gender_male   race  ethnicity  degree  ...  race_white  \
0            False        False  False      False   False  ...       False   
1            False        False  False       True   False  ...        True   
2            False        False  False      False   False  ...       False   
3            False        False  False      False   False  ...       False   
4            False        False  False      False   False  ...       False   
..             ...          ...    ...        ...     ...  ...         ...   
570          False        False  False      False   False  ...       False   
571          False        False  False      False   False  ...       False   
572          False        False  False      False   False  ...       False   
573          False        False  False      False   False  ...       False   
574          False        False  False      False   False  ...       False   

     MFQ_HARM_AVGscale  MFQ_FAIRNESS_AVGscale  MFQ_INGROUP_AVGscale  \
0                False                  False                 False   
1                False                  False                 False   
2                False                  False                 False   
3                False                  False                 False   
4                False                  False                 False   
..                 ...                    ...                   ...   
570              False                  False                 False   
571              False                  False                 False   
572              False                  False                 False   
573              False                  False                 False   
574              False                  False                 False   

     MFQ_AUTHORITY_AVGscale  MFQ_PURITY_AVGscale  MFQ_PROGRESSIVISMscale  \
0                     False                False                   False   
1                     False                False                   False   
2                     False                False                   False   
3                     False                False                   False   
4                     False                False                   False   
..                      ...                  ...                     ...   
570                   False                False                   False   
571                   False                False                   False   
572                   False                False                   False   
573                   False                False                   False   
574                   False                False                   False   

     no_trust  yes_trust  trust-science  
0       False      False          False  
1        True       True           True  
2       False      False          False  
3       False      False          False  
4       False      False          False  
..        ...        ...            ...  
570     False      False          False  
571      True       True           True  
572     False      False          False  
573  

In [11]:
knn.fit(df)
df_tr = knn.transform(df)

c:\Users\jerem\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\_param_validation.py:541: FutureWarning: Passing an int for a boolean parameter is deprecated in version 1.2 and won't be supported anymore in version 1.4.
  warnings.warn(


In [17]:
df2 = pd.DataFrame(df_tr)

In [18]:
df2.head()

0    1    2    3    4    5    6    7    8    9    ...  105  106  107  108  \
0  0.0  0.0  0.0  1.0  2.0  3.0  1.0  1.0  0.0  4.0  ...  0.0  0.0  0.0  0.0   
1  1.0  1.0  1.0  3.0  3.0  4.0  0.0  0.0  0.4  3.0  ...  1.0  0.0  0.0  0.0   
2  2.0  2.0  2.0  2.0  2.0  3.0  1.0  1.0  0.0  1.0  ...  0.0  0.0  0.0  0.0   
3  3.0  3.0  3.0  3.0  4.0  5.0  0.0  1.0  0.0  1.0  ...  0.0  0.0  0.0  0.0   
4  4.0  4.0  4.0  4.0  3.0  3.0  0.0  1.0  0.0  3.0  ...  0.0  0.0  0.0  0.0   

   109  110  111  112  113  114  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  1.0  1.0  1.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 115 columns]

In [19]:
print(df_tr)

[[  0.   0.   0. ...   0.   0.   0.]
 [  1.   1.   1. ...   1.   1.   1.]
 [  2.   2.   2. ...   0.   0.   0.]
 ...
 [572. 572. 572. ...   0.   0.   0.]
 [573. 573. 573. ...   0.   0.   0.]
 [574. 574. 574. ...   0.   0.   0.]]


In [20]:
df2.to_csv('imputed.csv')

In [4]:
df = pd.read_csv('imputed.csv')

In [22]:
df.head()

income  subjective_class  income_enough  gender_male  race  ethnicity  \
0     1.0                 2            3.0            1     1        0.0   
1     3.0                 3            4.0            0     0        0.4   
2     2.0                 2            3.0            1     1        0.0   
3     3.0                 4            5.0            0     1        0.0   
4     4.0                 3            3.0            0     1        0.0   

   degree  leftright   VHscale  COVIDthreat  prevent_behav  race_white  \
0     4.0        1.0  2.000000     3.833333       3.909091         1.0   
1     3.0        3.2  3.333333     2.666667       2.818182         0.8   
2     1.0        1.0  1.222222     4.333333       3.818182         1.0   
3     1.0        6.0  2.333333     3.166667       2.872727         1.0   
4     3.0        1.0  1.444444     4.833333       3.000000         1.0   

   MFQ_HARM_AVGscale  MFQ_FAIRNESS_AVGscale  MFQ_INGROUP_AVGscale  \
0           4.000000               4.333333              0.000000   
1           3.333333               2.833333              2.333333   
2           3.833333               5.000000              0.666667   
3           3.833333               3.166667              2.500000   
4           4.333333               4.833333              2.000000   

   MFQ_AUTHORITY_AVGscale  MFQ_PURITY_AVGscale  MFQ_PROGRESSIVISMscale  \
0                1.000000             0.666667                3.611111   
1                1.666667             2.166667                1.027778   
2                0.333333             0.166667                4.027778   
3                3.333333             2.166667                0.833333   
4                0.833333             0.166667                3.583333   

   trust-science  
0       1.523810  
1       1.152381  
2       1.571429  
3      -0.428571  
4       1.476190

In [5]:
df['income'].value_counts()

2.0    235
3.0    158
1.0    127
4.0     51
2.8      2
3.2      1
1.6      1
Name: income, dtype: int64

In [6]:
df['income'].replace([2.8,3.2,1.6],[3,3,2], inplace=True)
df['income'].value_counts()

2.0    236
3.0    161
1.0    127
4.0     51
Name: income, dtype: int64

In [7]:
df['subjective_class'].value_counts()

3    318
2    186
1     48
4     23
Name: subjective_class, dtype: int64

In [8]:
df['income_enough'].value_counts()

3.0    264
4.0    127
2.0     76
5.0     69
1.0     38
3.4      1
Name: income_enough, dtype: int64

In [9]:
df['income_enough'].replace([3.4],[3],inplace=True)
df['income_enough'].value_counts()

3.0    265
4.0    127
2.0     76
5.0     69
1.0     38
Name: income_enough, dtype: int64

In [10]:
df['gender_male'].value_counts()

0    333
1    242
Name: gender_male, dtype: int64

In [11]:
df['race_white'].value_counts()

1.0    521
0.0     45
0.8      7
0.6      2
Name: race_white, dtype: int64

In [12]:
df['race_white'].replace([0.8,0.6],[1,1],inplace=True)
df['race_white'].value_counts()

1.0    530
0.0     45
Name: race_white, dtype: int64

In [13]:
df['degree'].value_counts()

3.0    222
4.0    179
1.0    111
2.0     61
2.2      1
3.2      1
Name: degree, dtype: int64

In [14]:
df['degree'].replace([2.2,3.2],[2,3],inplace=True)
df['degree'].value_counts()

3.0    223
4.0    179
1.0    111
2.0     62
Name: degree, dtype: int64

In [16]:
df['leftright'].value_counts()

2.0    99
6.0    83
1.0    74
5.0    70
3.0    69
4.0    68
7.0    26
3.6    12
4.2    10
3.8     9
3.2     9
3.4     7
2.6     7
4.8     5
4.4     4
2.8     4
2.2     4
1.8     3
2.4     3
5.8     2
5.2     2
4.6     2
5.4     2
1.6     1
Name: leftright, dtype: int64

In [ ]:
df['left']
3.6    12
4.2    10
3.8     9
3.2     9
3.4     7
2.6     7
4.8     5
4.4     4
2.8     4
2.2     4
1.8     3
2.4     3
5.8     2
5.2     2
4.6     2
5.4     2
1.6     1

In [17]:
df.to_csv('imputed_recoded.csv')

In [20]:
df.isnull()

income  subjective_class  income_enough  gender_male   race  ethnicity  \
0     False             False          False        False  False      False   
1     False             False          False        False  False      False   
2     False             False          False        False  False      False   
3     False             False          False        False  False      False   
4     False             False          False        False  False      False   
..      ...               ...            ...          ...    ...        ...   
570   False             False          False        False  False      False   
571   False             False          False        False  False      False   
572   False             False          False        False  False      False   
573   False             False          False        False  False      False   
574   False             False          False        False  False      False   

     degree  leftright  VHscale  COVIDthreat  prevent_behav  race_white  \
0     False      False    False        False          False       False   
1     False      False    False        False          False       False   
2     False      False    False        False          False       False   
3     False      False    False        False          False       False   
4     False      False    False        False          False       False   
..      ...        ...      ...          ...            ...         ...   
570   False      False    False        False          False       False   
571   False      False    False        False          False       False   
572   False      False    False        False          False       False   
573   False      False    False        False          False       False   
574   False      False    False        False          False       False   

     MFQ_HARM_AVGscale  MFQ_FAIRNESS_AVGscale  MFQ_INGROUP_AVGscale  \
0                False                  False                 False   
1                False                  False                 False   
2                False                  False                 False   
3                False                  False                 False   
4                False                  False                 False   
..                 ...                    ...                   ...   
570              False                  False                 False   
571              False                  False                 False   
572              False                  False                 False   
573              False                  False                 False   
574              False                  False                 False   

     MFQ_AUTHORITY_AVGscale  MFQ_PURITY_AVGscale  MFQ_PROGRESSIVISMscale  \
0                     False                False                   False   
1                     False                False                   False   
2                     False                False                   False   
3                     False                False                   False   
4                     False                False                   False   
..                      ...                  ...                     ...   
570                   False                False                   False   
571                   False                False                   False   
572                   False                False                   False   
573                   False                False                   False   
574                   False                False                   False   

     trust-science  
0            False  
1            False  
2            False  
3            False  
4            False  
..             ...  
570          False  
571          False  
572          False  
573          False  
574          False  

[575 rows x 19 columns]